.build:
  stage: build
  image: $NODE_IMAGE
  cache:
    key:
      prefix: npm
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build
  artifacts:
    paths:
      - $DIST_DIR

npm preview:
  extends: .build
  needs:
    - vendor preview
  only:
    refs:
      - branches
  except:
    refs:
      - tags
  variables:
    REACT_APP_BASE_URL: $BASE_URL
    CI: ""

npm release:
  extends: .build
  environment:
    name: production
  only:
    refs:
      - tags
  needs:
    - vendor production
  variables:
    REACT_APP_BASE_URL: $BASE_URL
    CI: ""
