# Этот stage используется для установки и кеширования зависимостей

.vendor:
  stage: checkout
  image: $NODE_IMAGE
  interruptible: true
  before_script:
    - echo @yamaha-admin-sb:registry=https://$VERDACCIO_URL >> .npmrc
    - echo //$VERDACCIO_URL/:_authToken=$VERDACCIO_AUTH_TOKEN >> .npmrc
  script:
    - npm i
  cache:
    key:
      prefix: npm
      files:
        - package-lock.json
    paths:
      - node_modules/

vendor preview:
  extends: .vendor
  when: manual
  only:
    refs:
      - branches
  except:
    refs:
      - tags

vendor production:
  extends: .vendor
  when: always
  only:
    refs:
      - tags
