{{ if ne .Values.release_mode "production" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "trackableappname" . }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.domain }}`)
      services:
        - name: {{ template "trackableappname" . }}
          port: {{ .Values.service.externalPort }}
  tls:
    certResolver: httpdefault
    domains:
      - main: {{ .Values.ingress.domain }}
{{ end }}
