apiVersion: v1
kind: Service
metadata:
  name: {{ template "trackableappname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    service: {{ template "trackableappname" . }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http-{{ template "trackableappname" . }}
