service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
application:
  track: stable
  env: production

resourcesProd:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi
resourcesDev:
  limits:
    cpu: 30m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 32Mi

deployment:
  replicas:
    prod: 2
    dev: 1